// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dbf44ad8-91d9-4abb-a92d-ee60ea255a9f",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "f1f1394c30bd4725a2a11bd4057fbc82",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamofb19d929-amplify",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apianalytics",
            "endpoint": "https://1kdzvsr39a.execute-api.us-east-1.amazonaws.com/amplify",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
